AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for SNS-SQS demo using filter policies

Resources:
  ###################
  ##   SNS Topic   ##
  ###################
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: Topic
      TopicName: Topic
  ###################
  ##  SQS Queues   ##
  ###################
  ColorQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: ColorQueue
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt ColorDLQueue.Arn
        maxReceiveCount: 5
  BlueYellowQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: BlueYellowQueue
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt BlueYellowDLQueue.Arn
        maxReceiveCount: 5
  RedQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: RedQueue
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt RedDLQueue.Arn
        maxReceiveCount: 5
  GreenHighQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: GreenHighQueue
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt GreenHighDLQueue.Arn
        maxReceiveCount: 5
  GreenLowQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: GreenLowQueue
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt GreenLowDLQueue.Arn
        maxReceiveCount: 5
  ###################
  ## SQS DL Queues ##
  ###################
  ColorDLQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: ColorDLQueue
  BlueYellowDLQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: BlueYellowDLQueue
  RedDLQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: RedDLQueue
  GreenHighDLQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: GreenHighDLQueue
  GreenLowDLQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: GreenLowDLQueue
  #############################
  ##   SQS Access Policies   ##
  #############################
  # allows SNS Topic to publish to the queues
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ColorQueue
        - !Ref BlueYellowQueue
        - !Ref RedQueue
        - !Ref GreenHighQueue
        - !Ref GreenLowQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - sqs:SendMessage
            Resource: "*"
            Condition:
              ArnEquals: 
                aws:SourceArn:
                  !Ref SNSTopic
  ###########################
  ##   SNS Subscriptions   ##
  ###########################
  ###########################
  ##   SNS Filter Policy   ##
  ###########################
  ColorQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt ColorQueue.Arn
      Protocol: sqs
      RawMessageDelivery: True
      TopicArn: !Ref SNSTopic
  BlueYellowQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt BlueYellowQueue.Arn
      Protocol: sqs
      FilterPolicy:
        color:
          - blue
          - yellow
      RawMessageDelivery: True
      TopicArn: !Ref SNSTopic
  RedQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt RedQueue.Arn
      Protocol: sqs
      FilterPolicy:
        color:
          - red
      RawMessageDelivery: True
      TopicArn: !Ref SNSTopic
  GreenHighQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt GreenHighQueue.Arn
      Protocol: sqs
      FilterPolicy:
        color:
          - green
        number:
        - numeric:
          - ">"
          - 100
      RawMessageDelivery: True
      TopicArn: !Ref SNSTopic
  GreenLowQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt GreenLowQueue.Arn
      Protocol: sqs
      FilterPolicy:
        color:
          - green
        number:
          - numeric:
            - "<="
            - 100
      RawMessageDelivery: True
      TopicArn: !Ref SNSTopic